// Place things in increments of 5
var CANVAS_GRANULARITY = 5;
var INTERSECTION = {
    NO_INTERSECTION: 0,
    COLLINEAR: 1,
    DO_INTERSECT: 2
};
var CONTEXT_MENU_OPTIONS_VALUES = {
    DELETE_WIRE: 0
};
var CONTEXT_MENU_OPTIONS = [ CONTEXT_MENU_OPTIONS_VALUES.DELETE_WIRE ];
var DRAW_INTERVAL = 16;
var DEBUG = false;
var ZYANTE_GREEN = '#738033';
var ZYANTE_MEDIUM_RED = '#BB0404';
var ZYANTE_DARK_ORANGE = '#AB4600';
var DEFAULT_TEXT_COLOR = 'black';
var DEFAULT_WIDTH = 640;
var DEFAULT_HEIGHT = 480;
var NAMES = {};
var WIRE_COLOR = 'black';
var WIRE_BUFFER = 15;
var WIRE_LENGTH = 20;
var HALF_WIRE_LENGTH = WIRE_LENGTH / 2;
var QUARTER_WIRE_LENGTH = WIRE_LENGTH / 4;
var ZYANTE_DARK_BLUE = '#5780A6';
