'use strict';

/* exported ExpressionParserError */

/**
    An error generated by the expression parser.
    @class ExpressionParserError
*/
class ExpressionParserError {

    /**
        @constructor
        @param {String} error The message indicating the error.
        @param {String} [suggestion=''] A suggestion on how to address the error.
    */
    constructor(error, suggestion = '') {

        /**
            The message indicating the error.
            @type {String}
            @property error
        */
        this.error = error;

        /**
            A suggestion on how to address the error.
            @type {String}
            @property suggestion
        */
        this.suggestion = suggestion;
    }
}
